
#1. HTTP 요청 들어옴
#   ↓
#2. server 블록 선택
#   ↓
#3. SSL로 암호화 연결
#   ↓
#4. location 규칙 매칭
#   ↓
#5. 정적 파일 or PHP 처리

#동시에 처리할 수 있는 연결의 최대 개수
events
{
    worker_connections 3
}

http
{
    server
    {
        listen      443 ssl;
        server_name jisokim2.42.fr;

        # SSL 인증서 경로
        ssl_certificate /etc/ssl/certs/nginx.crt;
        ssl_certificate_key /etc/ssl/private/nginx.key;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;
        ssl_ciphers HIGH:!aNULL:!MD5;

        root /var/www/html;
        index index.php;

        # "URL 경로별로 어떻게 처리할지 정하는 규칙"
        location / 
        {
            try_files $uri $uri/ /index.php?$args;
        }

        location ~ \.php$
        {
            include fastcgi_params;
            fastcgi_pass wordpress:9000;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }
}