
# 1. HTTP request comes in
# 2. server block is selected
# 3. SSL encrypted connection
# 4. location rule matching
# 5. static file or PHP processing

# Maximum number of connections that can be processed simultaneously
events
{
    worker_connections 1024;
}

http
{
    server
    {
        listen      443 ssl;
        #TODO delete localhost;
        server_name jisokim2.42.fr localhost;

        # SSL certificate path
        ssl_certificate /etc/ssl/certs/nginx.crt;
        ssl_certificate_key /etc/ssl/private/nginx.key;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;
        ssl_ciphers HIGH:!aNULL:!MD5;

        root /var/www/html;
        index index.php;

        # "URL route rules"
        location / 
        {
            try_files $uri $uri/ /index.php?$args;
        }
        #fastcgi : just send the packet to php, no need to wait for php to finish.
        #because nginx is fast, it can't read php file. So send it to php in wordpress container.
        #and then php-fpm handles it and return it to nginx.
        
        # "PHP files processing rule" if no file name
        location ~ \.php$
        {
            fastcgi_pass   wordpress:9000;                                      #passing request to wordpress container through 9000 port(php-fpm)
            fastcgi_index  index.php;                                           #use index.php : it is a Entrypoint in Wordpress, so all request must go through this.
            include        fastcgi_params;
            fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;  #SCRIPT_FILENAME : It tells "which file should I execute right now?"
                                                                                #$document_root : root path.
                                                                                #$fastcgi_script_name : it is a name of the file that php-fpm should execute.
        }

        # "health check rule"
        location = /health
        {
            include fastcgi_params;
            fastcgi_pass wordpress:9000;
            fastcgi_param SCRIPT_FILENAME /var/www/html/health.php;
        }
    }
}