
# 1. HTTP request comes in
# 2. server block is selected
# 3. SSL encrypted connection
# 4. location rule matching
# 5. static file or PHP processing

# Maximum number of connections that can be processed simultaneously
events
{
    worker_connections 1024;
}

http
{
    server
    {
        listen      443 ssl;
        server_name jisokim2.42.fr localhost;

        # SSL certificate path
        ssl_certificate /etc/ssl/certs/nginx.crt;
        ssl_certificate_key /etc/ssl/private/nginx.key;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;
        ssl_ciphers HIGH:!aNULL:!MD5;

        root /var/www/html;
        index index.php;

        # "URL route rules"
        location / 
        {
            try_files $uri $uri/ /index.php?$args;
        }

        location ~ \.php$
        {
            fastcgi_pass   wordpress:9000;
            fastcgi_index  index.php;
            include        fastcgi_params;
            fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }

        location = /health
        {
            include fastcgi_params;
            fastcgi_pass wordpress:9000;
            fastcgi_param SCRIPT_FILENAME /var/www/html/health.php;
        }
    }
}